import "../globals.css";
import Image from "next/image";
import LandingSignInLight from '../../../public/landingSignIn-removebg-preview.png'
import LandingSignInDark from '../../../public/image.jpg'

export const metadata = {
  title: "Log In" ,
  description: "Generated by create next app",
};

export default function LoginLayout({ children }: childrenProps) {
  return (
    <div className="m-0 block sm:flex min-h-dvh">
      <div className="flex mb-5 sm:mb-0 sm:hidden md:w-1/2 lg:w-2/5 justify-center items-center md:flex bg-[#F3F5F7] dark:bg-black ">
        <Image
          src={LandingSignInLight}
          width={700}
          priority={true}
          className="max-w-full max-h-full object-contain dark:hidden"
          alt=""
        />
        <Image
          src={LandingSignInDark}
          width={700}
          priority={true}
          className="max-w-full hidden max-h-full object-contain dark:block"
          alt=""
        />
      </div>
      {children}
    </div>
  );
}
