import Header from "../components/Header";
import { cookies } from "next/headers.js";
import "../globals.css";
import { redirect } from "next/navigation";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children } : {children: React.ReactNode}) {
  const cookieStore = cookies();
  const cookie = cookieStore.get("token");
  if (!cookie) redirect("/login");
  return (
    <>
      <Header />
      <main className="flex flex-col flex-1">{children}</main>
    </>
  );
}
