import Header from "../components/Header";
import "../globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children } : {children: React.ReactNode}) {
  return (
    <>
      <Header />
      <main className="flex flex-col flex-1">{children}</main>
    </>
  );
}
