import { Inter } from "next/font/google";
import "./globals.css";
import { locales } from "../../navigation";
import { ThemeProvider } from "next-themes";
import { unstable_setRequestLocale } from "next-intl/server";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default function RootLayout({ children, params: {locale} }: childrenProps<paramsLang>) {
  unstable_setRequestLocale(locale);

  return (
      <html lang={locale} suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
        </ThemeProvider>
        </body>
      </html>
    );
}
