import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ka' }]
}

export default function RootLayout({ children, params: {locale} }: childrenProps<paramsLang>) {
    return (
      <html lang={locale} suppressHydrationWarning>
        <body className={inter.className + " h-dvh flex flex-col justify-center"}>
        <Providers>
            {children}
        </Providers>
        </body>
      </html>
    );
}
