import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children } : childrenProps) {
  return <main className="flex flex-col flex-1">{children}</main>;
}
