import { Inter } from "next/font/google";
import "./globals.css";
import { getDictionary } from "./dictionaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ka' }]
}

export default function RootLayout({ children, params: {lang} }) {


    return (
      <html lang={lang}>
        <body className={inter.className + " h-dvh flex flex-col justify-center"}>
          {children}
        </body>
      </html>
    );
}
